In [ ]:
#numpy --> package for numerical computing, To overcome limitations of Python ?
#array ??
#list --> collection of heterogenous type of elements
#import package
import numpy as np



In [ ]:
array1 = np.array([12,13,-7]) #1-D array

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
array2 = np.zeros((2,3)) #rows --> 2, columns --> 3

In [ ]:
array2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
array3 = np.empty((3,4)) #uninitialized

In [ ]:
array3

array([[4.68243518e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [ ]:
#2-D array
array_2d = np.array([[23,4,5],[-13,1,0]])
print(array_2d.flatten())

[ 23   4   5 -13   1   0]


In [ ]:
array_2d.shape

(2, 3)

In [ ]:
array_2d.dtype

dtype('int64')

In [ ]:
array_2d.data

In [ ]:
#array with random values
#seed
np.random.seed(13)
rand_array = np.random.rand(3)

In [ ]:
rand_array

array([0.77770241, 0.23754122, 0.82427853])

In [ ]:
np.random.seed(25)
rand_array_new = np.random.rand(3)

In [ ]:
rand_array_new

array([0.87012414, 0.58227693, 0.27883894])

In [ ]:
array_2d

array([[ 23,   4,   5],
       [-13,   1,   0]])

In [ ]:
array_2d = array_2d.T

In [ ]:
array_2d

array([[ 23, -13],
       [  4,   1],
       [  5,   0]])

In [ ]:
array_2d.size

6

In [ ]:
array_2d.ndim

2

In [ ]:
array_2d

array([[ 23, -13],
       [  4,   1],
       [  5,   0]])

In [ ]:
array_2d[2,0] #array[row_index,col_index]

5

In [ ]:
array_3d = np.arange(1,7) #arange
array_3d = array_3d.reshape((1,2,3)) #reshape

In [ ]:
array_3d.shape

(1, 2, 3)

In [ ]:
array1

array([12, 13, -7])

In [ ]:
#slicing
array1[1:3]

array([13, -7])

In [ ]:
array_2d

array([[ 23, -13],
       [  4,   1],
       [  5,   0]])

In [ ]:
#array_2d[2,0:2]
array_2d[2:,:]

array([[5, 0]])

In [ ]:
array_3d

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
#flatten
array_flattned=array_3d.flatten()

In [ ]:
array_flattned

array([1, 2, 3, 4, 5, 6])

In [ ]:
array1

array([12, 13, -7])

In [ ]:
height = [170,178,170,173]
weight = [80,76,70,70]

In [ ]:
#Element-wise addition : height + weight
height + weight #append

[170, 178, 170, 173, 80, 76, 70, 70]

In [ ]:
#for loop : Inefficient
height_array = np.array(height)
weight_array = np.array(weight)

In [ ]:
height_array * weight_array #Element-wise operation


array([13600, 13528, 11900, 12110])

In [ ]:
#Comparison Operation
height_array < weight_array

array([False, False, False, False])

In [ ]:
#Iterating over arrays
array_2d

array([[ 23, -13],
       [  4,   1],
       [  5,   0]])

In [ ]:
for i in np.nditer(array_2d): #nditer
  print(i)

23
4
5
-13
1
0


In [ ]:
#stride
array_2d

array([[ 23, -13],
       [  4,   1],
       [  5,   0]])

In [ ]:
array_2d.strides

(8, 24)

In [ ]:
array_2d.dtype

dtype('int64')

In [ ]:
#Mathematical Functions : Trigonometric Function
np.tan(np.pi/4)

0.9999999999999999

In [ ]:
#Inverse Trigonometric Function
np.degrees(np.arcsin(1))
np.degrees(np.arctan(1))

45.0

In [ ]:
#Hyperbolic Functions
np.sinh(0)
np.cosh(0)

1.0

In [ ]:
np.arcsinh(0)

0.0

In [ ]:
#Rounding Functions
f_array = np.array([0.1485,1.1726,2.99])

In [ ]:
#around --> lesser accurate but faster
np.around(f_array,2)

array([0.15, 1.17, 2.99])

In [ ]:
#round
np.round(f_array,2)

array([0.15, 1.17, 2.99])

In [ ]:
np.round(56294995342131.5, 3)

56294995342131.51

In [ ]:
np.around(56294995342131.5, 3)

56294995342131.51

In [ ]:
f_array = [12.3,1.3,4.5]

In [ ]:
np.rint(f_array) #rounding to nearest integer

array([12.,  1.,  4.])

In [ ]:
#fix
print(np.fix(f_array)) #floor

[12.  1.  4.]


In [ ]:
#floor, ceil
np.ceil(f_array)

array([1., 2., 3.])

In [ ]:
np.floor(f_array)

array([0., 1., 2.])

In [ ]:
#sum of array elements
f_array

array([0.1485, 1.1726, 2.99  ])

In [ ]:
np.sum(f_array)

4.311100000000001

In [ ]:
#nan --> not a number
np.nansum([2,np.nan,3])

5.0

In [ ]:
a= np.diff([13,4,2]) #1st discrete difference along given axis
print(np.diff(a))             #2nd discrete difference

[7]


In [ ]:
np.cumsum([3,4,12])

array([ 3,  7, 19])

In [ ]:
#Exponents & logarithms
a = np.array([2,3])

In [ ]:
np.exp(a)

array([ 7.3890561 , 20.08553692])

In [ ]:
2.718281**3

20.085518558602185

In [ ]:
#logarithms
np.log(a) #natural log
np.log10(a)

array([0.30103   , 0.47712125])

In [ ]:
new_array = np.array([221,13,245,0,1])

In [ ]:
new_array.mean()

96.0

In [ ]:
np.median(new_array)

13.0

In [ ]:
np.std(new_array)

17.204650534085253

In [ ]:
np.var(new_array)

296.0

In [ ]:
#covariance -value : +value
#correlation -1 to 1
q1 = np.array([12,32,56])
q2 = np.array([34,56,99])

In [ ]:
np.cov(q1,q2)

array([[ 485.33333333,  722.        ],
       [ 722.        , 1093.        ]])